# Generated by Django 6.0.1 on 2026-05-16 12:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
        ("courses", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="course",
            name="instructor",
            field=models.ForeignKey(
                limit_choices_to={"is_instructor_approved": True, "role": "instructor"},
                on_delete=django.db.models.deletion.CASCADE,
                related_name="courses",
                to="accounts.instructorprofile",
            ),
        ),
    ]
