# Generated by Django 6.0.1 on 2026-05-16 12:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
        ("courses", "0003_alter_course_instructor"),
    ]

    operations = [
        migrations.AlterField(
            model_name="course",
            name="instructor",
            field=models.ForeignKey(
                limit_choices_to={"is_verified": True},
                on_delete=django.db.models.deletion.CASCADE,
                related_name="courses",
                to="accounts.instructorprofile",
            ),
        ),
    ]
